<a href="https://colab.research.google.com/github/dbetm/DeepLearningLifeSciences/blob/main/Installation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!curl -Lo conda_installer.py https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py
import conda_installer
conda_installer.install()
!/root/miniconda/bin/conda info -e
!pip install --pre deepchem
import deepchem
deepchem.__version__

# DeepChem Datasets

In [4]:
import deepchem as dc
import numpy as np

In [7]:
# Wrap Numpy Arrays with NumpyDataset

x = np.random.random((4, 5))
y = np.random.random((4, 1))
print(x)
print(y)

# wrapping
dataset = dc.data.NumpyDataset(x, y)
print(dataset.X)
print(dataset.y)

[[0.92176724 0.89874566 0.65402688 0.47947964 0.95294077]
 [0.50496897 0.47911329 0.50389055 0.28578489 0.68156636]
 [0.51505825 0.8373001  0.91081071 0.64940008 0.6116178 ]
 [0.81516054 0.62830853 0.92330761 0.71554343 0.83682503]]
[[0.20778774]
 [0.43257896]
 [0.78922786]
 [0.8425518 ]]
[[0.92176724 0.89874566 0.65402688 0.47947964 0.95294077]
 [0.50496897 0.47911329 0.50389055 0.28578489 0.68156636]
 [0.51505825 0.8373001  0.91081071 0.64940008 0.6116178 ]
 [0.81516054 0.62830853 0.92330761 0.71554343 0.83682503]]
[[0.20778774]
 [0.43257896]
 [0.78922786]
 [0.8425518 ]]


Note: There are other types of Datasets objects, for example, for large dataset that it can't be enterely stored in computer memory.